# Configuration settings for LLM LoreSmith

# Application settings
app:
  name: "LLM LoreSmith"
  version: "0.1.0"
  description: "Fine-tune LLMs with credible documents"
  company: "Aulendur LLC"

# Deployment mode
deployment:
  mode: "local"  # Options: local, cloud
  debug: true

# Security settings
security:
  encryption_enabled: true
  access_control_enabled: true
  data_retention_days: 30

# UI Branding
ui:
  colors:
    primary: "#FFFEFB"
    secondary: "#7B949C"
    accent: "#5C798B"
    dark: "#213C4E"
    darker: "#182241"
  fonts:
    heading: "Oswald"
    body: "Nunito Sans"
    code: "Source Code Pro"

# Model settings
model:
  default_engine: "vllm"
  mcp_enabled: true
  default_epochs: 3
  max_epochs: 10
  evaluation_interval: 1

# Resource limits
resources:
  max_document_size_mb: 50
  max_dataset_size_mb: 500
  max_memory_usage_percent: 80
  max_cpu_usage_percent: 90
